version: "3"

services:
  front:
    build: ./front
    volumes:
      - ./front:/app
    ports:
      - "3002:3002"
    tty: true
    stdin_open: true
    command: npm run serve

volumes:
  mysql_data:
  bundle:
